swagger: '2.0'
x-stoplight:
  id: opbcj7fqgxaf4
info:
  title: Files-API
  version: '1.0'
host: 'localhost:5000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /list:
    parameters: []
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          schema:
            type: array
            items:
              type: object
              properties:
                file_name:
                  type: string
                id:
                  type: integer
                path:
                  type: string
                post_id:
                  type: integer
            x-examples:
              example-1:
                - file_name: 1685907898_5274txt
                  id: 1
                  path: uploads/documents
                  post_id: 123
          examples:
            example-1:
              - file_name: 1685907898_5274.txt
                id: 1
                path: uploads/documents
                post_id: 123
            example-2:
              message: A tabela está vazia
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
            x-examples:
              example-1:
                error: 'Something went wrong, please contact admin support'
          examples:
            example-1:
              error: 'Something went wrong, please contact admin support'
      operationId: get-all-files
      description: ''
  '/list/{post_id}':
    parameters:
      - type: number
        name: post_id
        in: path
        required: true
        description: Post ID
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          schema:
            type: array
            items:
              type: object
              properties:
                file_name:
                  type: string
                id:
                  type: integer
                path:
                  type: string
                post_id:
                  type: integer
            x-examples:
              example-1:
                - file_name: 1685907898_5274.txt
                  id: 1
                  path: uploads/documents
                  post_id: 123
          examples:
            example-1:
              - file_name: 1685907898_5274.txt
                id: 1
                path: uploads/documents
                post_id: 123
            example-2:
              message: A tabela está vazia
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
            x-examples:
              example-1:
                error: 'Something went wrong, please contact admin support'
          examples:
            example-1:
              error: 'Something went wrong, please contact admin support'
        '':
          schema:
            type: array
            items:
              type: object
              properties:
                file_name:
                  type: string
                id:
                  type: integer
                path:
                  type: string
                post_id:
                  type: integer
            x-examples:
              example-1:
                - file_name: 1685907898_5274txt
                  id: 1
                  path: uploads/documents
                  post_id: 123
      operationId: get-file-by-post-id
      description: ''
  /user:
    post:
      summary: Create New User
      operationId: upload-file
      responses:
        '200':
          description: User Created
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Missing Required Information
          schema:
            type: 'null'
        '409':
          description: Email Already Taken
          schema:
            type: 'null'
      description: ''
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              dateOfBirth:
                type: string
                format: date
            required:
              - firstName
              - lastName
              - email
              - dateOfBirth
          description: Post the necessary fields for the API to create a new user.
          x-examples:
            Create User Bob Fellow:
              firstName: Bob
              lastName: Fellow
              email: bob.fellow@gmail.com
              dateOfBirth: '1996-08-24'
  '/delete/{file_id}':
    parameters:
      - type: string
        name: file_id
        in: path
        required: true
        description: File ID
    delete:
      summary: Delete File
      operationId: delete-file-by-id
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
            x-examples:
              example-1:
                message: Image deleted successfully
          examples:
            example-1:
              message: Image deleted successfully
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              error:
                type: string
            x-examples:
              example-1:
                error: Image not found
          examples:
            example-1:
              error: 'Missing required parameter: file_id'
        '404':
          description: Not Found
          schema:
            type: object
            properties: {}
          examples:
            example-1:
              error: Image not found
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
            x-examples:
              example-1:
                error: Image not found
          examples:
            example-1:
              error: 'Something went wrong, please contact admin support'
definitions: {}
