swagger: '2.0'
x-stoplight:
  id: opbcj7fqgxaf4
info:
  title: Files-API
  version: '1.0'
host: 'localhost:5000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /list:
    parameters: []
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: Successful
          schema:
            type: array
            items:
              type: object
              properties:
                file_name:
                  type: string
                id:
                  type: integer
                path:
                  type: string
                post_id:
                  type: integer
            x-examples:
              example-1:
                - file_name: 1685907898_5274txt
                  id: 1
                  path: uploads/documents
                  post_id: 123
          examples:
            example-200-1:
              - file_name: 1685907898_5274.txt
                id: 1
                path: uploads/documents
                post_id: 123
            example-200-2:
              message: A tabela está vazia
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
            x-examples:
              example-1:
                error: 'Something went wrong, please contact admin support'
          examples:
            example-500:
              error: 'Something went wrong, please contact admin support'
      operationId: get-all-files
      description: Returns a list of all files saved in the database or a message indicating that the list is empty.
  '/list/{post_id}':
    parameters:
      - type: number
        name: post_id
        in: path
        required: true
        description: Post ID
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: Successful
          schema:
            type: array
            items:
              type: object
              properties:
                file_name:
                  type: string
                id:
                  type: integer
                path:
                  type: string
                post_id:
                  type: integer
            x-examples:
              example-1:
                - file_name: 1685907898_5274.txt
                  id: 1
                  path: uploads/documents
                  post_id: 123
          examples:
            example-200-1:
              - file_name: 1685907898_5274.txt
                id: 1
                path: uploads/documents
                post_id: 123
            example-200-2:
              message: A tabela está vazia
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
            x-examples:
              example-1:
                error: 'Something went wrong, please contact admin support'
          examples:
            example-500:
              error: 'Something went wrong, please contact admin support'
        '':
          schema:
            type: array
            items:
              type: object
              properties:
                file_name:
                  type: string
                id:
                  type: integer
                path:
                  type: string
                post_id:
                  type: integer
            x-examples:
              example-1:
                - file_name: 1685907898_5274txt
                  id: 1
                  path: uploads/documents
                  post_id: 123
      operationId: get-file-by-post-id
      description: Returns the list of files attached to a post.
  /upload:
    post:
      summary: Create New User
      operationId: upload-file
      responses:
        '200':
          description: Successful
          schema:
            type: object
            properties:
              '32':
                type: object
                properties:
                  file_id:
                    type: integer
                  filename:
                    type: string
                  path:
                    type: string
                  post_id:
                    type: string
            x-examples:
              example-1:
                '32':
                  file_id: 32
                  filename: 1687803337_6488.txt
                  path: uploads/documents
                  post_id: '345'
          examples:
            example-200:
              '32':
                file_id: 32
                filename: 1687803337_6488.txt
                path: uploads/documents
                post_id: '345'
        '400':
          description: Bad Request
          schema:
            type: object
            x-examples:
              example-1:
                txt_com_palavrao.txt: File content has bad words
            properties:
              filename.extension:
                type: string
              post_id:
                type: string
              files:
                type: string
          examples:
            example-400-1:
              fileWithBadWord.txt: File content has bad words
            example-400-2:
              filename.invalidExtension: File type is not allowed
            example-400-3:
              post_id: This is a required field
            example-400-4:
              files: This is a required field
            example-400-5:
              files: It must be a file
      description: Attach files to a post based on the Post Id.
      parameters:
        - in: formData
          type: array
          name: files
          description: File list
          required: true
        - in: formData
          type: number
          name: post_id
          description: Post ID
          required: true
    parameters: []
  '/delete/{file_id}':
    parameters:
      - type: string
        name: file_id
        in: path
        required: true
        description: File ID
    delete:
      summary: Delete File
      operationId: delete-file-by-id
      responses:
        '200':
          description: Successful
          schema:
            type: object
            properties:
              message:
                type: string
            x-examples:
              example-1:
                message: Image deleted successfully
          examples:
            example-200:
              message: File deleted successfully
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              error:
                type: string
            x-examples:
              example-1:
                error: Image not found
          examples:
            example-400:
              error: 'Missing required parameter: file_id'
        '404':
          description: Not Found
          schema:
            type: object
            properties: {}
          examples:
            example-404:
              error: File not found
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
            x-examples:
              example-1:
                error: Image not found
          examples:
            example-500:
              error: 'Something went wrong, please contact admin support'
      description: Deletes a file attached to a post based on its Id.
definitions: {}
